# -*- coding: utf-8 -*-
"""Ecommerce_Sales_Analysis_InternCircle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzuASEm-67FQo_u-y03VmDOcYwca3X0w
"""

# ============================================================
# INTERN CIRCLE - E-COMMERCE SALES TREND ANALYSIS
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("=" * 60)
print("       E-COMMERCE SALES TREND ANALYSIS")
print("=" * 60)

# ------------------------------------------------------------
# 1. LOAD DATASET
# ------------------------------------------------------------

# Using a sample e-commerce dataset
url = "https://raw.githubusercontent.com/leonism/sample-superstore/master/data/superstore.csv"

df = pd.read_csv(url)
print("\n1. DATASET LOADED SUCCESSFULLY")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# ------------------------------------------------------------
# 2. BASIC DATA EXPLORATION
# ------------------------------------------------------------

print("\n2. FIRST 5 ROWS")
display(df.head())

print("\n3. DATASET INFORMATION")
df.info()

print("\n4. COLUMN NAMES")
print(df.columns.tolist())

print("\n5. STATISTICAL SUMMARY")
display(df.describe())

# ------------------------------------------------------------
# 3. DATA CLEANING
# ------------------------------------------------------------

print("\n6. MISSING VALUES")
print(df.isnull().sum())

print("\n7. DUPLICATE RECORDS")
print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

# ------------------------------------------------------------
# 4. DATE CONVERSION
# ------------------------------------------------------------

df["Order Date"] = pd.to_datetime(df["Order Date"])

print("\n8. DATE COLUMN CONVERTED SUCCESSFULLY")

# ------------------------------------------------------------
# 5. FEATURE ENGINEERING
# ------------------------------------------------------------

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month_Name"] = df["Order Date"].dt.month_name()
df["Year_Month"] = df["Order Date"].dt.to_period("M").astype(str)

print("\n9. FEATURE ENGINEERING COMPLETED")
print("New features: Year, Month, Month_Name, Year_Month")

# ------------------------------------------------------------
# 6. REVENUE ANALYSIS
# ------------------------------------------------------------

total_sales = df["Sales"].sum()

print("\n10. TOTAL REVENUE")
print("Total Sales: $", round(total_sales, 2))

# ------------------------------------------------------------
# 7. SALES BY YEAR
# ------------------------------------------------------------

yearly_sales = df.groupby("Year")["Sales"].sum().sort_index()

print("\n11. YEARLY SALES")
display(yearly_sales.round(2))

# ------------------------------------------------------------
# 8. MONTHLY SALES TREND
# ------------------------------------------------------------

monthly_sales = df.groupby("Year_Month")["Sales"].sum()

print("\n12. MONTHLY SALES TREND")
display(monthly_sales.round(2))

# ------------------------------------------------------------
# 9. SALES BY CATEGORY
# ------------------------------------------------------------

category_sales = (
    df.groupby("Category")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n13. SALES BY CATEGORY")
display(category_sales.round(2))

# ------------------------------------------------------------
# 10. SALES BY SUB-CATEGORY
# ------------------------------------------------------------

subcategory_sales = (
    df.groupby("Sub-Category")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n14. TOP SUB-CATEGORIES")
display(subcategory_sales.head(10).round(2))

# ------------------------------------------------------------
# 11. TOP CUSTOMERS
# ------------------------------------------------------------

customer_sales = (
    df.groupby("Customer Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n15. TOP 10 CUSTOMERS")
display(customer_sales.head(10).round(2))

# ------------------------------------------------------------
# 12. CUSTOMER SEGMENT ANALYSIS
# ------------------------------------------------------------

segment_sales = (
    df.groupby("Segment")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n16. SALES BY CUSTOMER SEGMENT")
display(segment_sales.round(2))

# ------------------------------------------------------------
# 13. REGION ANALYSIS
# ------------------------------------------------------------

region_sales = (
    df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n17. SALES BY REGION")
display(region_sales.round(2))

# ------------------------------------------------------------
# 14. PIVOT TABLE
# ------------------------------------------------------------

pivot_table = pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

print("\n18. CATEGORY VS REGION PIVOT TABLE")
display(pivot_table.round(2))

# ------------------------------------------------------------
# 15. YEAR + CATEGORY PIVOT
# ------------------------------------------------------------

year_category_pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Year",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

print("\n19. YEAR VS CATEGORY PIVOT TABLE")
display(year_category_pivot.round(2))

# ------------------------------------------------------------
# 16. TOP PRODUCTS
# ------------------------------------------------------------

product_sales = (
    df.groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n20. TOP 10 PRODUCTS")
display(product_sales.head(10).round(2))

# ------------------------------------------------------------
# 17. SALES VISUALIZATION - MONTHLY TREND
# ------------------------------------------------------------

plt.figure(figsize=(14, 6))

plt.plot(
    monthly_sales.index,
    monthly_sales.values,
    marker="o"
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 18. CATEGORY SALES CHART
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

category_sales.plot(kind="bar")

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 19. CUSTOMER SEGMENT CHART
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

segment_sales.plot(kind="bar")

plt.title("Sales by Customer Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 20. REGION SALES CHART
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

region_sales.plot(kind="bar")

plt.title("Sales by Region")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 21. CUSTOMER SEGMENT PERCENTAGE
# ------------------------------------------------------------

segment_percentage = (
    segment_sales / segment_sales.sum() * 100
)

print("\n21. CUSTOMER SEGMENT CONTRIBUTION (%)")
display(segment_percentage.round(2))

# ------------------------------------------------------------
# 22. BEST PERFORMING MONTH
# ------------------------------------------------------------

best_month = monthly_sales.idxmax()
best_month_sales = monthly_sales.max()

print("\n22. BEST SALES MONTH")
print("Month:", best_month)
print("Sales: $", round(best_month_sales, 2))

# ------------------------------------------------------------
# 23. BEST CATEGORY
# ------------------------------------------------------------

best_category = category_sales.idxmax()
best_category_sales = category_sales.max()

print("\n23. BEST CATEGORY")
print("Category:", best_category)
print("Sales: $", round(best_category_sales, 2))

# ------------------------------------------------------------
# 24. BEST REGION
# ------------------------------------------------------------

best_region = region_sales.idxmax()
best_region_sales = region_sales.max()

print("\n24. BEST REGION")
print("Region:", best_region)
print("Sales: $", round(best_region_sales, 2))

# ------------------------------------------------------------
# 25. BUSINESS RECOMMENDATIONS
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("             BUSINESS RECOMMENDATIONS")
print("=" * 60)

print("\n1. Focus marketing efforts on the highest-performing")
print("   customer segment.")

print("\n2. Increase inventory and promotional campaigns for")
print("   the highest-selling category.")

print("\n3. Study the best-performing region and identify")
print("   strategies that can be applied to weaker regions.")

print("\n4. Prepare seasonal campaigns around months with")
print("   historically high sales.")

print("\n5. Identify high-value customers and use loyalty")
print("   programs or personalized offers to retain them.")

print("\n6. Monitor low-performing products and categories")
print("   to improve pricing, marketing, or inventory decisions.")

# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("              FINAL ANALYSIS SUMMARY")
print("=" * 60)

print("Total Revenue: $", round(total_sales, 2))
print("Best Month:", best_month)
print("Best Category:", best_category)
print("Best Region:", best_region)
print("Top Customer:", customer_sales.index[0])
print("Top Product:", product_sales.index[0])

print("\nE-COMMERCE SALES ANALYSIS COMPLETED SUCCESSFULLY!")